FROM python:3.6

ENV PIP_DISABLE_PIP_VERSION_CHECK=on
WORKDIR /app
COPY poetry.lock pyproject.toml manage.py /app/

RUN pip3.6 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

COPY backend backend

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]